### ISSUE TITLE
评论系统是不是有点问题啊？

### ISSUE THREAD

**Issue by zhangshen147** [ike-c/hexo-theme-inside#102]
我看作者博客的评论系统就加载不出来，我自己在_config.yml里面先后配置的valine和gitalk也都没生效。

**Comment by ike-c** [comment]
没问题啊，贴一下配置看看

**Comment by zhangshen147** [comment]
Valine是这样：
``` 
plugins:
  - //cdn1.lncld.net/static/js/3.0.4/av-min.js
  - //unpkg.com/valine/dist/Valine.min.js
  - position: comments
    template: |
      <div id="vcomment"></div>
      <script>
        new Valine({
          el: '#vcomment',
          appId: 'H8lpKTp3dNadvRj8tBVP6Mtt-gzGzoHsz',
          appKey: 'mp2MaA3XvOi64B3XroDUqjvJ',
          path: location.pathname
        })
      </script>
```
什么都不显示

**Comment by ike-c** [comment]
经测试是正常的，测试版本 [2.3.0-beta.1](https://github.com/ike-c/hexo-theme-inside/releases/tag/2.3.0-beta.1)。
但看你的网站是 valine 依赖的这两个 js 文件没有插入模板，看下你是不是改了 `layout/index.ejs`，或者不是最新版？

**Comment by shuntan** [comment]
兄弟 appId 和 appKey 都发出来。。。

**Comment by zhangshen147** [comment]
> 兄弟 appId 和 appKey 都发出来。。。

感觉评论系统也就起个交流作用，无所谓了。。

**Comment by ike-c** [comment]
@zhangshen147 如果还有问题，欢迎提出来~

**Comment by wolf03** [comment]
@zhangshen147 我的 valine 评论配置一添加 placeholder 值就会报错，看到你的可用，想问一问这个问题怎么解决

**Comment by zhangshen147** [comment]
> @zhangshen147 我的 valine 评论配置一添加 placeholder 值就会报错，看到你的可用，想问一问这个问题怎么解决

这是我的配置文件，猜想你的问题可能是出在逗号、引号这些问题上了：
```
plugins:
  - //cdn1.lncld.net/static/js/3.0.4/av-min.js
  - //unpkg.com/valine/dist/Valine.min.js
  - position: comments
    template: |
      <div id="vcomment"></div>
      <script>
        new Valine({
          el: '#vcomment',
          appId: 'aaaaaaaaaaaaaaa',
          appKey: 'bbbbbbbbbbbbb',
          path: location.pathname,
	      placeholder: '道路千万条，文明第一条。\n评论不规范，亲人两行泪',
	      notify: false,
	      verify: false,
	      visitor: true,
	      recordIP: true
        })
      </script>
```

**Comment by zhangshen147** [comment]
> @zhangshen147 如果还有问题，欢迎提出来~

不知道问题出在哪里，不过更新到新版本后就好了，之前忘记反馈了。。

**Comment by zhangshen147** [comment]
> @zhangshen147 如果还有问题，欢迎提出来~

不知道问题出在哪里，不过更新到新版本后就好了，之前忘记反馈了。。

**Comment by wolf03** [comment]
嗯，已经弄好了。感谢😆


------------------ 原始邮件 ------------------
发件人: "zhangshen147"<notifications@github.com>;
发送时间: 2019年7月16日(星期二) 下午3:35
收件人: "ike-c/hexo-theme-inside"<hexo-theme-inside@noreply.github.com>;
抄送: "&nbsp;"<903517499@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ike-c/hexo-theme-inside] 评论系统是不是有点问题啊？ (#102)



 
@zhangshen147 我的 valine 评论配置一添加 placeholder 值就会报错，看到你的可用，想问一问这个问题怎么解决
  
这是我的配置文件，猜想你的问题可能是出在逗号、引号这些问题上了：
 plugins:   - //cdn1.lncld.net/static/js/3.0.4/av-min.js   - //unpkg.com/valine/dist/Valine.min.js   - position: comments     template: |       <div id="vcomment"></div>       <script>         new Valine({           el: '#vcomment',           appId: 'aaaaaaaaaaaaaaa',           appKey: 'bbbbbbbbbbbbb',           path: location.pathname, 	      placeholder: '道路千万条，文明第一条。\n评论不规范，亲人两行泪', 	      notify: false, 	      verify: false, 	      visitor: true, 	      recordIP: true         })       </script>
