### ISSUE TITLE
啥时候支持post_asset_folder路由吖？

### ISSUE THREAD

**Issue by shuntan** [ike-c/hexo-theme-inside#104]
## 如题

> https://hexo.io/zh-cn/docs/asset-folders.html#%E6%96%87%E7%AB%A0%E8%B5%84%E6%BA%90%E6%96%87%E4%BB%B6%E5%A4%B9

以前的文章的资源文件都在对应文章的文件夹里（：哭）
全部移到image/里不利于管理呢...

**Comment by ike-c** [comment]
没用过，现在不行吗

**Comment by shuntan** [comment]
可以，只不过只能{% asset_img 图片文件名 [title] %}这样写。用markdown语法或者html写相对路径就不行...

**Comment by ike-c** [comment]
这个简单，只要一行代码，你可以先暂时自己改代码 [lib/filter/post.js#L108](https://github.com/ike-c/hexo-theme-inside/blob/master/lib/filter/post.js#L108)：
```diff
    // assets
    $('img').each(function () {
      const img$ = $(this), src = img$.attr('src');
-      src && img$.attr('src', uriReplacer(src))
+      src && img$.attr('src', `/${link}/${src}`)
    });
```

**Comment by shuntan** [comment]
你好像误会我的意思了，我的意思是路径完全正确的情况下。
* `1: <img src="/post/文章1/281557578598_.pic_hd.jpg"/> `
* `2: ![](/post/文章1/281557578598_.pic_hd.jpg) `
* `3: {% asset_img 281557578598_.pic_hd.jpg %} `

1和2就不行，3就行。

奇怪了，html生成的内容都是`<img src="/post/文章1/281557578598_.pic_hd.jpg"/> 
`
好像中文的路径才会出现这种情况？encode了也不行

**Comment by ike-c** [comment]
因为你没设置 permalink

```yml
permalink: post/:title/
```

**Comment by ike-c** [comment]
@shuntan 我刚改了点代码，也可以不写完整路径了，如 `![](281557578598_.pic_hd.jpg)`，另外这个 permalink 也做了兼容
