### ISSUE TITLE
大佬可以支持下文章置顶吗

### ISSUE THREAD

**Issue by OuYanghaoyue** [ike-c/hexo-theme-inside#105]
大佬可以支持下文章置顶吗？很想使用文章置顶的功能

**Comment by ike-c** [comment]
官方有这个功能吗

**Comment by OuYanghaoyue** [comment]
官网没有但是可以实现，https://blog.minhow.com/2017/08/20/hexo/article-top/  原谅我太菜了搞不来

**Comment by ike-c** [comment]
似乎很简单，已经支持了，[2.3.0-beta.3](https://github.com/ike-c/hexo-theme-inside/releases/tag/2.3.0-beta.3)

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： hexojs/hexo-generator-index#51
