### ISSUE TITLE
代码越界，不能左右滑动

### ISSUE THREAD

**Issue by toperc** [ike-c/hexo-theme-inside#107]
升级到最新版本2.3.0-rc.0 后，小屏幕手机上观看，代码越界不能左右滑动，你看一下哪里的问题

**Comment by ike-c** [comment]
给个问题链接

**Comment by toperc** [comment]
> 
> 
> 给个问题链接

我对比看了一下是三个“`”的代码块没有和上边文字空一行的原因，以前包括在其他平台上没有发现过

**Comment by ike-c** [comment]
有没有链接，我在我的网站上暂时没发现问题

**Comment by toperc** [comment]
> 
> 
> 有没有链接，我在我的网站上暂时没发现问题

https://toperc.com/blog/post/1521647039
https://toperc.com/blog/post/1522163597

这两个你可以看一下。  
正文引用代码块和在列表中引用代码块（需要缩进一个制表）都出现了这个问题，正文引用代码块可以接受代码块前空一行或者前后都空行，但是在列表中代码块前空一行却不起作用，如果代码块后也空一行就导致列表排序格式失败了。

我在csdn、简书上以及有道云笔记上都没有这个问题，主题的前几个版本也没有发现这个问题。

### 这里顺便做一个测试

代码块与本行不空行
```java
public void test(){
}
```

代码块与本行空一行

```java
public void test(){
}
```

结果：不空行、空一行或者前后都空行都没问题。

下边是列表：
1. 列表第一行
    ```java
    public void test(){
    }
    ```
    结果：代码块与列表第一行没有空行，正常显示。

2. 列表第二行

    ```java
    public void test(){
    }
    ```

   结果：代码块前后都有空行，正常显示。
3. 列表第三行

**Comment by ike-c** [comment]
正常的结构应是这样的
![image](https://user-images.githubusercontent.com/9206414/61178880-1c580800-a5ac-11e9-8c17-e7b31b41c4e1.png)

但你的少了一层标签
![image](https://user-images.githubusercontent.com/9206414/61178891-490c1f80-a5ac-11e9-8532-b1b96475fa0b.png)

看下你是不是自己改了 lib/filter/post.js 这个文件

**Comment by toperc** [comment]
> 
> 
> 正常的结构应是这样的
> ![image](https://user-images.githubusercontent.com/9206414/61178880-1c580800-a5ac-11e9-8c17-e7b31b41c4e1.png)
> 
> 但你的少了一层标签
> ![image](https://user-images.githubusercontent.com/9206414/61178891-490c1f80-a5ac-11e9-8532-b1b96475fa0b.png)
> 
> 看下你是不是自己改了 lib/filter/post.js 这个文件

没有改，你把下边的创建一个文件你试一下，看看效果

```````````````
## 这里顺便做一个测试

### 正文引用代码块

代码块与本行不空行
```java
public void test(){
    。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
}
```

代码块与本行空一行

```java
public void test(){
    。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
}
```

### 列表引用代码块

1. 列表第一行
    ```java
    public void test(){
        。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
    }
    ```
    代码块与列表第一行没有空行

2. 列表第二行

    ```java
    public void test(){
        。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
    }
    ```

   代码块前后都有空行

3. 列表第三行
```````````````

这是我这边的效果：

![测试](https://note.youdao.com/yws/api/personal/file/016EDE763E9C476EAD82CA3D9D94CC5B?method=download&shareKey=c795109de5941dd6e6d380d8d37854cd)

**Comment by ike-c** [comment]
是我理解错了，默认只处理了独立的代码块，嵌套就不行了，已改好，你试下 [42cc44c](https://github.com/ike-c/hexo-theme-inside/commit/42cc44c20fef893f2558f6d73ba7e199ebc3d48f)。

**Comment by toperc** [comment]
完美，解决了
