### ISSUE TITLE
printing style

### ISSUE THREAD

**Issue by SakyaVarro** [ike-c/hexo-theme-inside#108]
作者您好，我在使用 [arachnys/athenapdf](https://github.com/arachnys/athenapdf) 抓取我的[简历页面](http://sakyavarro.cn/resume/)并生成 PDF，现在遇到的问题是，简历页面的内容很长，但生成的 PDF 只有一页。我向 [arachnys/athenapdf](https://github.com/arachnys/athenapdf) 提交了 [issue](https://github.com/arachnys/athenapdf/issues/197)，得到的回复是：

> The behaviour is expected. Your website was designed with a div set to match exactly the height of the screen, and to overflow. I'd suggest applying some print specific styles to remove the height: 100%, and any overflow.

如果作者可以为打印、生成 PDF 应用专门的样式，我将感激不尽。

网站的截图：
![image](https://user-images.githubusercontent.com/24671424/61179828-2249f980-a63d-11e9-8695-b335c5a6a28c.png)

生成的 PDF 的截图：
![image](https://user-images.githubusercontent.com/24671424/61179831-35f56000-a63d-11e9-92a4-5cc3adb9452b.png)

网站链接： [http://sakyavarro.cn/resume](http://sakyavarro.cn/resume)
athenapdf issue 链接： [https://github.com/arachnys/athenapdf/issues/197](https://github.com/arachnys/athenapdf/issues/197)

**Comment by ike-c** [comment]
可以加用于打印的样式，但没那么快，你可以先自己改
```css
@media print {

}
```

**Comment by SakyaVarro** [comment]
嗯。我试下（不过我是后端开发，对前端不熟，可能还是要等你开发吧）。总之，先谢了。
