### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by wolf03** [ike-c/hexo-theme-inside#109]
先说一个小bug：
支付宝三个字没打全😂
![bug](https://ws2.sinaimg.cn/large/575d445cly1g4zjc5m2scj20aa05s749.jpg)

然后就是想问下，
发现这个网站的侧边栏调色样式更好看了，想问一下怎么弄，感觉像是 plugins 写出来的，如果可以发教程，请问能不能发到我的邮箱里？wolf0813cy@gmail.com如果可以，我将不胜感激

还有一点，就是看到您有做阅读统计的想法，这里献上 Valine 的策略，希望能帮到你。
https://valine.js.org/visitor.html

**Comment by ike-c** [comment]
是将“支”字作为图标用。
那个调色板是 plugins 写的，相当简单，我的网站虽然压缩，但代码很少，你可以去研究下，关于如何在浏览器端生成不同的主题的 CSS，参考这里 [#99](https://github.com/ike-c/hexo-theme-inside/issues/99#issuecomment-510122015) 。
统计的会提供一个机制用于更新前端显示，但具体使用什么服务，自己玩了（结合 plugins，应该很方便），主题不集成。

**Comment by wolf03** [comment]
@ike-c 调色板那部分有些看不懂，能说的简单些，或者直接把文件发给我吗？麻烦了

**Comment by ike-c** [comment]
1. 先预设几组样式配置，如 `{ accent_color: red }`, `{ accent_color: blue }`，`background`, `mode` 等这些字段也都是可以的，其实就是将主题 YAML 配置文件的 appearance 配置项转成 JS 对象；
2. 遍历配置数组，生成相应背景色的 HTML 标签，再绑定下点击事件；
3. 点击发生的时候调 `__inside__.$appearance(config)` 生成 CSS 代码；
4. 将 CSS 应用到网站不需要多说了吧。

**Comment by wolf03** [comment]
@ikeq 感觉还是太难。只会写网页样式，不会这些，果然新手就不该问这种高级问题😂
