### ISSUE TITLE
能不能显示文章阅读数、网站浏览量等统计数据功能？

### ISSUE THREAD

**Issue by q569608465** [ike-c/hexo-theme-inside#39]
能不能显示文章阅读数、网站浏览量等统计数据功能？

**Comment by xuxusheng** [comment]
同求~能集成某个统计服务就好了

**Comment by toperc** [comment]
有些人不一定喜欢这个功能，害怕服务中断显示不正常，如果集成的话最好找个权威的统计服务，然后主题中添加一个开关配置，根据个人喜好做设置。

**Comment by lttzz** [comment]
建议有这方面需求的看一看[不蒜子](http://busuanzi.ibruce.info/)呢
