### ISSUE TITLE
请问一下这个主题不支持hexo-tag-aplayer吗？

### ISSUE THREAD

**Issue by kencin** [ike-c/hexo-theme-inside#82]
主题很好看，但是我的文章里面很多都带了音乐，所以对这个插件的需求有点高。

**Comment by ike-c** [comment]
这个主题和别的主题的区别是：**是个 SPA，也就是说路由跳转不会导致页面刷新**，但自定义 tag 以及 markdown 里写 `<script>` 是支持的。

我看了下这个 hexo-tag-aplayer，对单页应用的支持似乎不是很好，应该能跑起来，但存在内存泄漏风险，建议自己去集成 APlayer。

**Comment by ike-c** [comment]
这个主题和别的主题的区别是：**是个 SPA，也就是说路由跳转不会导致页面刷新**，但自定义 tag 以及 markdown 里写 `<script>` 是支持的。

我看了下这个 hexo-tag-aplayer，应该能跑起来，如果有报错可以提出来，另外对于内存泄漏风险，可能需要改一下插件源码，插件首页 pjax 兼容的代码此主题是用不了的。
