### ISSUE TITLE
代码块的样式问题

### ISSUE THREAD

**Issue by YHaoNan** [ike-c/hexo-theme-inside#83]
https://lilpig.site/post/vscode-command

比如这篇文章，第一个代码块是正常的，第二个就有问题了，但是我看了css也没啥不一样的地方啊，不知道为啥显示会出错。

**Comment by elmorec** [comment]
确实，是个样式问题，多谢反馈！

**Comment by ike-c** [comment]
我仔细看了下，又发现没有你说的这个问题了，请更新到最新的文件再试试~
