### ISSUE TITLE
文章摘要设置

### ISSUE THREAD

**Issue by awnawnawn** [ike-c/hexo-theme-inside#84]
我在设置page文章的摘要遇到问题了，它没能显示出来，请问是meta的设置吗
![Snipaste_2019-06-09_16-30-53](https://user-images.githubusercontent.com/47672657/59156827-65f89300-8ad4-11e9-8c08-a00f4b3a5aaa.png)
********************
![Snipaste_2019-06-09_16-31-50](https://user-images.githubusercontent.com/47672657/59156829-66912980-8ad4-11e9-9151-2f3b5d492090.png)

**Comment by ike-c** [comment]
page 没有摘要，meta 只是显示 page 的 date 字段。

如果指 post 摘要，hexo 官方有说明 https://hexo.io/docs/tag-plugins#Post-Excerpt。
