### ISSUE TITLE
404页面

### ISSUE THREAD

**Issue by shuntan** [ike-c/hexo-theme-inside#91]
-1.当存在自己自定义的404页面时,utils.js 会编译不过。

**Comment by ike-c** [comment]
不确定这两者之间有什么关联，贴报错看看

**Comment by shuntan** [comment]
![image](https://user-images.githubusercontent.com/24288891/60148584-4cf61e80-9804-11e9-84c7-a0585970812c.png)

> 当存在如上的目录结构时，_post同级目录包含404/tags/categories文件夹且存在index.md文件时。可能会导致2个错误：

![image](https://user-images.githubusercontent.com/24288891/60148763-f50be780-9804-11e9-8af5-4ef6d69c3402.png)

- 错误1: 已存在自定义的404页面时，编译会报错。

![image](https://user-images.githubusercontent.com/24288891/60148807-1f5da500-9805-11e9-8f0c-70d56df17a2a.png)

- 错误2: 存在tags文件夹且包含一个空的index.md (注：type=tags)时，生成的tags页面，tag无法正常显示，如上图所示。

**Comment by ike-c** [comment]
额，如果你的自定义 page 和以下内置路由冲突，你懂的。

## 内置路由
- **page/:page** post 列表，如 `page/2`, `page/3`
- **post/:slug** post，如 `post/hello-word`
- **categories, tags, archives**
- **search**
- **404**

单纯支持下自定义 404 页面倒是不复杂，不过意义不大吧，特别是在这个主题里，能发挥的空间也不大（只能用 markdown 折腾）。

**Comment by shuntan** [comment]
嗯，我懂你的意思。但是我觉得包括我在内的大部分人，在配置你的主题之前可能就已经存在这些page页了，在不知情的情况下初次使用可能会遇到一些困惑...譬如我一开始就花了一丢丢时间定位了一下这个冲突问题。我觉得兼容的话会对使用者更加友好一些😊，你觉得呢？

**Comment by ike-c** [comment]
我是准备兼容来着，[2.3.0-rc.1](https://github.com/ike-c/hexo-theme-inside/releases/tag/2.3.0-rc.1)
