### ISSUE TITLE
toc 分级有误

### ISSUE THREAD

**Issue by shuntan** [ike-c/hexo-theme-inside#94]
1.存在h4,h5...等标题时，生成的toc有问题。
2.[建议] 能否兼容hexo-abbrlink plugin？

**Comment by ike-c** [comment]
啥问题贴一下

**Comment by shuntan** [comment]
> 啥问题贴一下
----
大概就是这个问题，不知道是我的md写法不够标准还是生成的静态页toc本身就存在缺陷。

![WechatIMG38](https://user-images.githubusercontent.com/24288891/60098921-2e067680-9789-11e9-845a-6811c99a826e.png)

<img width="973" alt="“361561465514_ pic_hd”的副本" src="https://user-images.githubusercontent.com/24288891/60098923-3068d080-9789-11e9-9882-17c8997c7d74.png">

**Comment by ike-c** [comment]
麻烦贴一下 markdown 代码，只贴几个标题的写法就够

**Comment by shuntan** [comment]
> 麻烦贴一下 markdown 代码，只贴几个标题的写法就够

```
# This is H1

test H1

#  This is  H1

test H1

# This is H2

test H2

### This is  H3

- std::mutex

- std::recursive_mutex

- std::time_mutex

- std::recursive_timed_mutex

<!-- more -->

####  This is  H4

test H4
```

**Comment by ike-c** [comment]
以下是我的测试结果，

![image](https://user-images.githubusercontent.com/9206414/60106190-58f7c700-9797-11e9-90e0-26fbbe7a633e.png)

ToC 解析为 3 个一级标题，没毛病。

至于 h3, h4 为毛没解析，因为不存在 h2，如果你有装类似 markdownlint 的语法检查工具，应该能看到像下面这样的提示，另外也有个类似的 issue #37。

![image](https://user-images.githubusercontent.com/9206414/60106564-01a62680-9798-11e9-9579-0cf0d57f0fb9.png)

**Comment by ike-c** [comment]
另外你的第二条建议 hexo-abbrlink，恐怕无法兼容，但这个功能不错，可以加，等我不太懒了……
在此之前，你可以自己尝试改源码。

**Comment by shuntan** [comment]
抱歉！第一个问题的原因是因为我装了hexo-all-minifier这个插件导致的... 不是你的问题。
