### ISSUE TITLE
希望能兼容hexo的豆瓣插件

### ISSUE THREAD

**Issue by lenhoo** [ike-c/hexo-theme-inside#97]
很喜欢作者的主题
插件地址：[hexo-douban](https://github.com/mythsman/hexo-douban)

**Comment by ike-c** [comment]
无法兼容，是插件不兼容主题~

**Comment by ike-c** [comment]
无法兼容，是插件不兼容主题~

**Comment by lenhoo** [comment]
> 无法兼容，是插件不兼容主题~

好的，感谢回复
